### ISSUE TITLE
Error  AttributeError: 'NIVisaLibrary' object has no attribute 'viParseRsrcEx'

### ISSUE THREAD

**Issue by labodezao** [AlexZettler/Rigol1000z#1]
Running your exemple code run.py provided by you, I get this error :

```
runfile('/home/zao/Téléchargements/Rigol1000z-master/examples/Bodeplot.py', wdir='/home/zao/Téléchargements/Rigol1000z-master/examples')
VISA Resources:  ('USB3::0x1ab1::0x04ce::\t',)
Traceback (most recent call last):

  File "/home/zao/Téléchargements/Rigol1000z-master/examples/Bodeplot.py", line 97, in <module>
    scope = rm.open_resource(rm.list_resources()[0])

  File "/home/zao/anaconda3/lib/python3.7/site-packages/pyvisa/highlevel.py", line 1750, in open_resource
    info = self.resource_info(resource_name, extended=True)

  File "/home/zao/anaconda3/lib/python3.7/site-packages/pyvisa/highlevel.py", line 1704, in resource_info
    ret, err = self.visalib.parse_resource_extended(self.session, resource_name)

  File "/home/zao/anaconda3/lib/python3.7/site-packages/pyvisa/ctwrapper/functions.py", line 1380, in parse_resource_extended
    ret = library.viParseRsrcEx(session, resource_name, byref(interface_type),

AttributeError: 'NIVisaLibrary' object has no attribute 'viParseRsrcEx'
```

**Comment by labodezao** [comment]
I can't get reed of this, I tryed with almost all the version of python, Pyvisa and I have always errors, and screenshoot are blanks as well as the csv files ....

**Comment by labodezao** [comment]
Okay, after a day of mess, I finally create a conda environement that is portable for linux ;)

**Comment by labodezao** [comment]
[tableacco.zip](https://github.com/AlexZettler/Rigol1000z/files/5473823/tableacco.zip)

[accolist.txt](https://github.com/AlexZettler/Rigol1000z/files/5472122/accolist.txt)

**Comment by labodezao** [comment]
https://github.com/charkster/rigol_ds1054z
https://github.com/AlexZettler/Rigol1000z
PyusbPyserial
https://www.raspberrypi.org/forums/viewtopic.php?t=87510
ls -l /dev/a*  (pour savoir les acces aux usb)
echo 'SUBSYSTEM=="usb", MODE="0660", GROUP="plugdev"' > /etc/udev/rules.d/00-usb-permissions.rules udevadm control --reload-rules
Add the following line to /etc/udev/rules.d/99-com.rules:SUBSYSTEM=="usb", MODE="0666", GROUP="usbusers"Create the 99-com.rules file if necessary.Then add your user to the usbusers groupsudo groupadd usbuserssudo usermod -a -G usbusers USERNAME
